Issue6
fullstacktf/personal-nutritionist-frontend pull request #13
Opened 2021-12-10 12:07 UTC by AdanRL

Footer component done

2021-12-10 20:15 UTC, elenamsd requested changes
add the logo images in public folder

2021-12-12 12:10 UTC, elenamsd approved these changes
😋

2021-12-13 11:17 UTC, mnzgarcia requested changes

2021-12-13 11:17 UTC, mnzgarcia commented on src/App.css
> +.app-div{
```suggestion
.app-div {
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +import {Grid}  from "@mui/material";
```suggestion
import { Grid }  from "@mui/material";
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +export default function Footer(){
```suggestion
export default function Footer() {
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +      <Grid item xs={12} md={2} sx={{display: "flex", alignItems: "center", justifyContent: "center"}}>
```suggestion
      <Grid item xs={12} md={2} sx={{ display: "flex", alignItems: "center", justifyContent: "center" }}>
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +        <img src='/assets/avocado.png' style={{ height: "100px", width: "100px"}} alt="Icono de un aguacate"/>
```suggestion
        <img src='/assets/avocado.png' style={{ height: "100px", width: "100px" }} alt="Icono de un aguacate"/>
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +          <Grid item xs={12} md={12} sx={{display: "flex", flexDirection: "column"}}>
```suggestion
          <Grid item xs={12} md={12} sx={{ display: "flex", flexDirection: "column" }}>
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +            <a href="a"><img style={{ height: "40px", width: "40px"}} src='/assets/Facebook.png' alt="facebook icon"/></a>
```suggestion
            <a href="a"><img style={{ height: "40px", width: "40px" }} src='/assets/Facebook.png' alt="facebook icon"/></a>
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +            <a href="a"><img style={{ height: "40px", width: "40px"}} src='/assets/Twitter.png' alt="twitter icon"/></a>
```suggestion
            <a href="a"><img style={{ height: "40px", width: "40px" }} src='/assets/Twitter.png' alt="twitter icon"/></a>
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +            <a href="https://www.instagram.com/nutriguide_es/"><img style={{ height: "40px", width: "40px"}} src='/assets/Instagram.png' alt="instragram icon"/></a>
```suggestion
            <a href="https://www.instagram.com/nutriguide_es/"><img style={{ height: "40px", width: "40px" }} src="/assets/Instagram.png" alt="instragram icon"/></a>
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +      <Grid item xs={12} md={4} sx={{display: "flex", flexDirection: "column"}}>
```suggestion
      <Grid item xs={12} md={4} sx={{ display: "flex", flexDirection: "column" }}>
```

2021-12-13 11:17 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +      <Grid item xs={12} md={2} sx={{display: "flex", alignItems: "center", justifyContent: "center"}}>
```suggestion
      <Grid item xs={12} md={2} sx={{ display: "flex", alignItems: "center", justifyContent: "center" }}>
```

2021-12-13 11:27 UTC, mnzgarcia approved these changes

2021-12-13 11:28 UTC, merged