Unite components NavBar, Footer and MarketingCard in Home Page
fullstacktf/personal-nutritionist-frontend pull request #18
Opened 2021-12-12 18:45 UTC by elenamsd

Fix #17

2021-12-13 11:08 UTC, AdanRL approved these changes

2021-12-14 13:30 UTC, AdanRL approved these changes

2021-12-14 13:33 UTC, AdanRL approved these changes

2021-12-14 13:38 UTC, mnzgarcia requested changes

2021-12-14 13:38 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +  backgroundColor:"#937A61",
```suggestion
  backgroundColor: "#937A61",
```

2021-12-14 13:38 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
>    return(
```suggestion
  return (
```

2021-12-14 13:38 UTC, mnzgarcia commented on src/components/Footer/Footer.tsx
> +
```suggestion
```

2021-12-14 13:38 UTC, mnzgarcia commented on src/components/MarketingCard/MarketingCard.tsx
>  import {styled} from "@mui/material/styles";
```suggestion
import { styled } from "@mui/material/styles";
```

2021-12-14 13:38 UTC, mnzgarcia commented on src/pages/Home/Home.tsx
> +  backgroundColor:"#f8f5f2",
```suggestion
  backgroundColor: "#f8f5f2",
```

2021-12-14 13:50 UTC, mnzgarcia requested changes

2021-12-14 13:50 UTC, mnzgarcia commented on src/components/Footer/__tests__/Footer.test.tsx
```suggestion
```

2021-12-14 13:50 UTC, mnzgarcia commented on src/components/MarketingCard/MarketingCard.tsx
>            sx={{ width:{xs: 150, md: 300, lg: 400} }}
```suggestion
          sx={{ width: {xs: 150, md: 300, lg: 400} }}
```

2021-12-14 13:50 UTC, mnzgarcia commented on src/components/NavBar/NavBar.tsx
> +        <ButtonLogIn
```suggestion
        <ButtonLogIn variant="text" endIcon={<AccountCircle />}>
```

2021-12-14 13:50 UTC, mnzgarcia commented on src/components/NavBar/NavBar.tsx
>            variant="text"
```suggestion
```

2021-12-14 13:50 UTC, mnzgarcia commented on src/components/NavBar/NavBar.tsx
>            endIcon={<AccountCircle />}
```suggestion
```

2021-12-14 13:50 UTC, mnzgarcia commented on src/components/NavBar/NavBar.tsx
>          >
```suggestion
```

2021-12-14 13:52 UTC, mnzgarcia approved these changes
👌🏽

2021-12-14 13:52 UTC, merged